const mongoose = require("mongoose");
require("dotenv").config();
const Plant = require("../models/Plant");

const plants = [
  {
    commonName: "Ashwagandha",
    hindiName: "अश्वगंधा",
    botanicalName: "Withania somnifera",
    sanskritName: "Ashwagandha",
    family: "Solanaceae",
    origin: "India, Africa",
    category: "Immunity",
    tags: ["Stress Relief", "Immunity", "Sleep"],
    description: "One of the most important herbs in Ayurvedic medicine, used for over 3,000 years to relieve stress and improve concentration.",
    medicinalUses: ["Stress reduction", "Improves sleep quality", "Boosts immune function"],
    activeCompounds: ["Withanolides", "Withaferin A", "Alkaloids"],
    precautions: "Contraindicated during pregnancy.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Tropical", "Arid"],
      difficulty: "Moderate",
      growthRate: "Slow-Moderate",
      harvestTime: "8-12 months",
      partUsed: "Root, leaf",
    },
    images: [],
    studiesCited: 47,
  },
  {
    commonName: "Holy Basil",
    hindiName: "तुलसी",
    botanicalName: "Ocimum tenuiflorum",
    sanskritName: "Tulsi",
    family: "Lamiaceae",
    origin: "India",
    category: "Immunity",
    tags: ["Immunity", "Respiratory"],
    description: "Known as Tulsi, this sacred plant is widely used in Ayurveda for respiratory and immune support.",
    medicinalUses: ["Boosts immunity", "Supports respiratory health", "Reduces inflammation"],
    activeCompounds: ["Ursolic acid", "Eugenol", "Rosmarinic acid"],
    precautions: "Generally safe, GRAS status.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "3-4 months",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 31,
  },
  {
    commonName: "Rhodiola",
    hindiName: "रोडियोला",
    botanicalName: "Rhodiola rosea",
    family: "Crassulaceae",
    origin: "Arctic regions, Europe, Asia",
    category: "Energy",
    tags: ["Energy", "Stress"],
    description: "An adaptogenic herb traditionally used to combat fatigue and improve mental performance under stress.",
    medicinalUses: ["Reduces fatigue", "Improves mental performance", "Stress adaptation"],
    activeCompounds: ["Rosavins", "Salidroside", "Tyrosol"],
    precautions: "Use with caution during pregnancy.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate",
      soil: "Rocky, poor soil",
      climate: ["Alpine", "Arctic"],
      difficulty: "Expert",
      growthRate: "Very Slow",
      harvestTime: "3-5 years",
      partUsed: "Root",
    },
    images: [],
    studiesCited: 23,
  },
  {
    commonName: "Turmeric",
    hindiName: "हल्दी",
    botanicalName: "Curcuma longa",
    sanskritName: "Haridra",
    family: "Zingiberaceae",
    origin: "South Asia",
    category: "Anti-inflammatory",
    tags: ["Anti-inflammatory", "Digestion"],
    description: "A golden-colored rhizome widely used in Ayurveda for its anti-inflammatory and antioxidant properties, central to Indian cuisine and traditional medicine alike.",
    medicinalUses: ["Reduces inflammation", "Supports joint health", "Aids digestion"],
    activeCompounds: ["Curcumin", "Turmerone", "Curcuminoids"],
    precautions: "May interact with blood thinners; avoid high doses before surgery.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Moderate",
      harvestTime: "8-10 months",
      partUsed: "Rhizome",
    },
    images: [],
    studiesCited: 62,
  },
  {
    commonName: "Lavender",
    hindiName: "लैवेंडर",
    botanicalName: "Lavandula angustifolia",
    family: "Lamiaceae",
    origin: "Mediterranean",
    category: "Stress Relief",
    tags: ["Stress", "Sleep"],
    description: "A fragrant flowering herb long used for its calming aroma, commonly applied in aromatherapy to ease anxiety and support restful sleep.",
    medicinalUses: ["Reduces anxiety", "Improves sleep quality", "Soothes skin irritation"],
    activeCompounds: ["Linalool", "Linalyl acetate"],
    precautions: "Generally safe; may cause mild skin irritation in essential oil form.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Temperate", "Mediterranean"],
      difficulty: "Easy",
      growthRate: "Moderate",
      harvestTime: "2-3 months (flowers)",
      partUsed: "Flower",
    },
    images: [],
    studiesCited: 38,
  },
  {
    commonName: "Echinacea",
    hindiName: "इचिनेशिया",
    botanicalName: "Echinacea purpurea",
    family: "Asteraceae",
    origin: "North America",
    category: "Immunity",
    tags: ["Immunity", "Respiratory"],
    description: "A purple-flowered plant traditionally used by Native Americans, popularly taken today to shorten the duration of colds and support immune response.",
    medicinalUses: ["Boosts immune response", "May reduce cold duration", "Anti-inflammatory"],
    activeCompounds: ["Alkamides", "Polysaccharides", "Caffeic acid derivatives"],
    precautions: "Not recommended for autoimmune conditions; consult a doctor first.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Well-drained, tolerates poor soil",
      climate: ["Temperate"],
      difficulty: "Moderate",
      growthRate: "Moderate",
      harvestTime: "Year 2 onward",
      partUsed: "Root, flower",
    },
    images: [],
    studiesCited: 29,
  },
  {
    commonName: "Chamomile",
    hindiName: "बबूने का फूल",
    botanicalName: "Matricaria chamomilla",
    family: "Asteraceae",
    origin: "Europe, Western Asia",
    category: "Sleep",
    tags: ["Sleep", "Digestion"],
    description: "A daisy-like flower widely brewed as a calming tea, traditionally used to ease digestive discomfort and promote relaxation before sleep.",
    medicinalUses: ["Promotes relaxation", "Eases digestive discomfort", "Mild anti-inflammatory"],
    activeCompounds: ["Apigenin", "Bisabolol", "Chamazulene"],
    precautions: "May cause allergic reaction in those sensitive to ragweed family plants.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Well-drained",
      climate: ["Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "6-8 weeks",
      partUsed: "Flower",
    },
    images: [],
    studiesCited: 34,
  },
  {
    commonName: "Ginger",
    hindiName: "अदरक",
    botanicalName: "Zingiber officinale",
    sanskritName: "Ardraka",
    family: "Zingiberaceae",
    origin: "Southeast Asia",
    category: "Digestion",
    tags: ["Digestion", "Anti-inflammatory"],
    description: "A pungent, warming rhizome used across traditional medicine systems to relieve nausea, aid digestion, and reduce inflammation.",
    medicinalUses: ["Relieves nausea", "Aids digestion", "Reduces inflammation"],
    activeCompounds: ["Gingerol", "Shogaol", "Zingerone"],
    precautions: "May interact with blood thinners at high doses.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate",
      soil: "Loamy, rich in organic matter",
      climate: ["Tropical"],
      difficulty: "Moderate",
      growthRate: "Slow",
      harvestTime: "8-10 months",
      partUsed: "Rhizome",
    },
    images: [],
    studiesCited: 55,
  },
  {
    commonName: "Peppermint",
    hindiName: "पिपरमिंट",
    botanicalName: "Mentha piperita",
    family: "Lamiaceae",
    origin: "Europe",
    category: "Digestion",
    tags: ["Digestion", "Headache", "Respiratory"],
    description: "A hybrid mint known for its cooling menthol content, commonly used to relieve headaches, digestive issues, and respiratory congestion.",
    medicinalUses: ["Relieves headaches", "Eases IBS symptoms", "Clears respiratory congestion"],
    activeCompounds: ["Menthol", "Menthone", "Rosmarinic acid"],
    precautions: "May worsen acid reflux in some individuals.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate",
      soil: "Moist, well-drained",
      climate: ["Temperate"],
      difficulty: "Easy",
      growthRate: "Fast (invasive spreader)",
      harvestTime: "6-8 weeks",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 27,
  },
  {
    commonName: "Aloe Vera",
    hindiName: "घृतकुमारी",
    botanicalName: "Aloe barbadensis miller",
    sanskritName: "Kumari",
    family: "Asphodelaceae",
    origin: "Arabian Peninsula",
    category: "Skin Care",
    tags: ["Skin Care", "Digestion"],
    description: "A succulent plant whose gel is widely used to soothe burns, moisturize skin, and support digestive health when taken internally in small amounts.",
    medicinalUses: ["Soothes burns and wounds", "Moisturizes skin", "Supports digestion"],
    activeCompounds: ["Aloin", "Acemannan", "Anthraquinones"],
    precautions: "Oral use in large amounts can cause laxative effects; avoid during pregnancy.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Arid", "Tropical"],
      difficulty: "Easy",
      growthRate: "Slow",
      harvestTime: "Year-round (mature leaves)",
      partUsed: "Leaf gel",
    },
    images: [],
    studiesCited: 41,
  },
  {
    commonName: "Brahmi",
    hindiName: "ब्राह्मी",
    botanicalName: "Bacopa monnieri",
    sanskritName: "Brahmi",
    family: "Plantaginaceae",
    origin: "India, wetlands of South Asia",
    category: "Cognitive",
    tags: ["Cognitive", "Stress"],
    description: "A creeping herb central to Ayurvedic brain tonics, traditionally used to enhance memory, learning, and cognitive performance.",
    medicinalUses: ["Enhances memory", "Reduces anxiety", "Supports cognitive function"],
    activeCompounds: ["Bacosides", "Alkaloids", "Saponins"],
    precautions: "May cause mild GI upset; consult doctor if on thyroid medication.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "High (thrives in wet soil)",
      soil: "Moist, marshy",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Moderate",
      harvestTime: "3-4 months",
      partUsed: "Whole plant",
    },
    images: [],
    studiesCited: 26,
  },
  {
    commonName: "Shatavari",
    hindiName: "शतावरी",
    botanicalName: "Asparagus racemosus",
    sanskritName: "Shatavari",
    family: "Asparagaceae",
    origin: "India, Himalayas",
    category: "Hormonal",
    tags: ["Hormonal", "Immunity"],
    description: "A climbing plant traditionally used in Ayurveda as a female reproductive tonic and adaptogen, valued for hormonal and immune support.",
    medicinalUses: ["Supports hormonal balance", "Adaptogenic stress support", "Boosts immunity"],
    activeCompounds: ["Saponins (shatavarins)", "Flavonoids"],
    precautions: "Consult a doctor if pregnant or on hormone-related medication.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Slow",
      harvestTime: "12-18 months",
      partUsed: "Root",
    },
    images: [],
    studiesCited: 19,
  },
  {
    commonName: "Neem",
    hindiName: "नीम",
    botanicalName: "Azadirachta indica",
    sanskritName: "Nimba",
    family: "Meliaceae",
    origin: "Indian subcontinent",
    category: "Skin Care",
    tags: ["Skin Care", "Immunity"],
    description: "A fast-growing tree deeply rooted in Ayurvedic tradition, prized for its antibacterial and antifungal properties in skin care and immune support.",
    medicinalUses: ["Treats skin infections", "Antibacterial/antifungal", "Supports immune function"],
    activeCompounds: ["Azadirachtin", "Nimbin", "Quercetin"],
    precautions: "Avoid internal use during pregnancy; not for long-term high-dose use.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Well-drained, tolerates poor soil",
      climate: ["Tropical", "Arid"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "Year-round (leaves)",
      partUsed: "Leaf, bark, seed",
    },
    images: [],
    studiesCited: 44,
  },
  {
    commonName: "Licorice",
    hindiName: "मुलेठी",
    botanicalName: "Glycyrrhiza glabra",
    sanskritName: "Yashtimadhu",
    family: "Fabaceae",
    origin: "Mediterranean, Asia",
    category: "Respiratory",
    tags: ["Respiratory", "Digestion"],
    description: "A sweet-rooted plant used to soothe sore throats, calm coughs, and ease digestive inflammation in traditional medicine systems.",
    medicinalUses: ["Soothes sore throat", "Eases cough", "Reduces digestive inflammation"],
    activeCompounds: ["Glycyrrhizin", "Flavonoids"],
    precautions: "Long-term use may raise blood pressure; avoid with hypertension.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Deep, well-drained",
      climate: ["Temperate", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Slow",
      harvestTime: "3-4 years",
      partUsed: "Root",
    },
    images: [],
    studiesCited: 22,
  },
  {
    commonName: "Fenugreek",
    hindiName: "मेथी",
    botanicalName: "Trigonella foenum-graecum",
    sanskritName: "Methi",
    family: "Fabaceae",
    origin: "Mediterranean, South Asia",
    category: "Digestion",
    tags: ["Digestion", "Blood Sugar"],
    description: "A seed-bearing herb widely used in Indian cooking and traditional medicine to support healthy blood sugar levels and digestion.",
    medicinalUses: ["Supports blood sugar regulation", "Aids digestion", "May boost lactation"],
    activeCompounds: ["Trigonelline", "4-hydroxyisoleucine", "Saponins"],
    precautions: "May interact with diabetes medication; avoid excess during pregnancy.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Well-drained loam",
      climate: ["Subtropical", "Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "3-4 months",
      partUsed: "Seed, leaf",
    },
    images: [],
    studiesCited: 33,
  },
  {
    commonName: "Basil",
    hindiName: "बेसिल",
    botanicalName: "Ocimum basilicum",
    family: "Lamiaceae",
    origin: "Central Africa, Southeast Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Aromatic"],
    description: "A fragrant culinary herb essential to Italian and Southeast Asian cooking, prized for its sweet, peppery leaves used fresh in everything from pesto to garnishes.",
    medicinalUses: ["Mild digestive aid", "Anti-inflammatory compounds", "Traditionally used for colds"],
    activeCompounds: ["Eugenol", "Linalool", "Estragole"],
    precautions: "Generally safe as a culinary herb in normal food amounts.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "3-4 weeks",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 18,
  },
  {
    commonName: "Cilantro (Coriander)",
    hindiName: "धनिया",
    botanicalName: "Coriandrum sativum",
    family: "Apiaceae",
    origin: "Mediterranean, Southwest Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Garnish"],
    description: "Known as coriander leaf or dhania, this bright, citrusy herb is a staple garnish across Indian, Mexican, and Southeast Asian cuisines, with seeds also used as a distinct spice.",
    medicinalUses: ["Aids digestion", "Mild antioxidant properties", "Traditionally used for bloating"],
    activeCompounds: ["Linalool", "Coriandrin", "Flavonoids"],
    precautions: "Generally safe; rare allergic reactions possible.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Well-drained, sandy loam",
      climate: ["Temperate", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "3-4 weeks",
      partUsed: "Leaf, seed",
    },
    images: [],
    studiesCited: 14,
  },
  {
    commonName: "Curry Leaf",
    hindiName: "करी पत्ता",
    botanicalName: "Murraya koenigii",
    sanskritName: "Kadi Patta",
    family: "Rutaceae",
    origin: "India, Sri Lanka",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Hair Care"],
    description: "A pungent, aromatic leaf essential to South Indian tempering and curries, also traditionally used in hair oils for scalp health.",
    medicinalUses: ["Supports digestion", "Traditionally used for hair health", "Antioxidant properties"],
    activeCompounds: ["Mahanimbine", "Koenigine", "Flavonoids"],
    precautions: "Generally safe in culinary amounts.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Slow",
      harvestTime: "6-12 months (young plant)",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 16,
  },
  {
    commonName: "Rosemary",
    hindiName: "रोज़मेरी",
    botanicalName: "Salvia rosmarinus",
    family: "Lamiaceae",
    origin: "Mediterranean",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Cognitive"],
    description: "A woody, pine-scented herb widely used in roasted dishes and breads, with a long folk history of being linked to memory and mental clarity.",
    medicinalUses: ["May support memory and focus", "Anti-inflammatory properties", "Antioxidant-rich"],
    activeCompounds: ["Rosmarinic acid", "Carnosic acid", "Cineole"],
    precautions: "Avoid medicinal-strength doses during pregnancy; culinary use is safe.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Mediterranean", "Temperate"],
      difficulty: "Easy",
      growthRate: "Slow-Moderate",
      harvestTime: "2-3 months",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 25,
  },
  {
    commonName: "Thyme",
    hindiName: "थाइम",
    botanicalName: "Thymus vulgaris",
    family: "Lamiaceae",
    origin: "Mediterranean",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Respiratory"],
    description: "A small, fragrant herb central to Mediterranean cooking, also traditionally brewed as a tea to ease coughs and sore throats.",
    medicinalUses: ["Eases cough", "Antimicrobial properties", "Supports respiratory comfort"],
    activeCompounds: ["Thymol", "Carvacrol"],
    precautions: "Generally safe in culinary amounts.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Mediterranean", "Temperate"],
      difficulty: "Easy",
      growthRate: "Slow",
      harvestTime: "2-3 months",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 21,
  },
  {
    commonName: "Oregano",
    hindiName: "ओरिगैनो",
    botanicalName: "Origanum vulgare",
    family: "Lamiaceae",
    origin: "Mediterranean, Western Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Immunity"],
    description: "A robust, peppery herb central to Italian and Greek cuisine, with a reputation for strong antioxidant and antimicrobial properties.",
    medicinalUses: ["Antimicrobial properties", "Rich in antioxidants", "Traditionally used for digestion"],
    activeCompounds: ["Carvacrol", "Thymol", "Rosmarinic acid"],
    precautions: "Generally safe in culinary amounts; avoid high-dose oil during pregnancy.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Well-drained, tolerates poor soil",
      climate: ["Mediterranean", "Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "2-3 months",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 20,
  },
  {
    commonName: "Parsley",
    hindiName: "अजमोद",
    botanicalName: "Petroselinum crispum",
    family: "Apiaceae",
    origin: "Mediterranean",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Garnish"],
    description: "A bright, versatile garnish herb used across global cuisines, notably rich in vitamins A, C, and K relative to its small serving size.",
    medicinalUses: ["Rich in vitamins A, C, K", "Mild diuretic properties", "Supports fresh breath"],
    activeCompounds: ["Apigenin", "Myristicin", "Flavonoids"],
    precautions: "Avoid large medicinal doses during pregnancy; culinary use is safe.",
    careGuide: {
      sunlight: "Full Sun to Partial Shade",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Temperate"],
      difficulty: "Easy",
      growthRate: "Moderate",
      harvestTime: "6-8 weeks",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 12,
  },
  {
    commonName: "Lemongrass",
    hindiName: "नींबू घास",
    botanicalName: "Cymbopogon citratus",
    family: "Poaceae",
    origin: "South Asia, Southeast Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Stress Relief"],
    description: "A citrusy, aromatic grass essential to Thai and Southeast Asian cooking, also popularly brewed as a calming, digestive-friendly tea.",
    medicinalUses: ["Aids digestion", "Calming aromatic properties", "Traditionally used for mild anxiety"],
    activeCompounds: ["Citral", "Geraniol", "Myrcene"],
    precautions: "Generally safe as tea/culinary use.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "4-6 months",
      partUsed: "Leaf, stalk",
    },
    images: [],
    studiesCited: 17,
  },
  {
    commonName: "Sage",
    hindiName: "सेज",
    botanicalName: "Salvia officinalis",
    family: "Lamiaceae",
    origin: "Mediterranean",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Cognitive"],
    description: "An earthy, savory herb popular in stuffings and roasted dishes, traditionally associated with mental clarity and throat soothing.",
    medicinalUses: ["May support memory", "Soothes sore throat", "Antioxidant properties"],
    activeCompounds: ["Rosmarinic acid", "Camphor", "Thujone"],
    precautions: "Avoid high medicinal doses during pregnancy due to thujone content; culinary use is safe.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Mediterranean", "Temperate"],
      difficulty: "Easy",
      growthRate: "Slow-Moderate",
      harvestTime: "2-3 months",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 19,
  },
  {
    commonName: "Dill",
    hindiName: "सोआ",
    botanicalName: "Anethum graveolens",
    family: "Apiaceae",
    origin: "Mediterranean, South Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Digestion"],
    description: "A feathery, slightly tangy herb used widely for pickling and fish dishes, with a long folk history as a gentle digestive aid.",
    medicinalUses: ["Eases digestive discomfort", "Traditionally used for infant colic (as gripe water)", "Mild antimicrobial properties"],
    activeCompounds: ["Carvone", "Limonene", "Flavonoids"],
    precautions: "Generally safe in culinary amounts.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Loamy, well-drained",
      climate: ["Temperate"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "6-8 weeks",
      partUsed: "Leaf, seed",
    },
    images: [],
    studiesCited: 13,
  },
  {
    commonName: "Mint",
    hindiName: "पुदीना",
    botanicalName: "Mentha spicata",
    family: "Lamiaceae",
    origin: "Mediterranean, Asia",
    category: "Culinary",
    tags: ["Culinary", "Kitchen Garden", "Digestion"],
    description: "A refreshing, versatile herb used in chutneys, teas, and garnishes across nearly every global cuisine, distinct from peppermint's stronger menthol profile.",
    medicinalUses: ["Eases digestive discomfort", "Freshens breath", "Mild cooling, calming aroma"],
    activeCompounds: ["Carvone", "Limonene"],
    precautions: "Generally safe as tea/culinary herb.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "Moderate to High",
      soil: "Moist, well-drained",
      climate: ["Temperate", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Fast (invasive spreader)",
      harvestTime: "4-6 weeks",
      partUsed: "Leaf",
    },
    images: [],
    studiesCited: 15,
  },
  {
    commonName: "Moringa",
    hindiName: "सहजन",
    botanicalName: "Moringa oleifera",
    sanskritName: "Shigru",
    family: "Moringaceae",
    origin: "South Asia",
    category: "Immunity",
    tags: ["Immunity", "Nutrition", "Culinary"],
    description: "Known as the 'drumstick tree,' its leaves and pods are used both as a highly nutritious vegetable and in Ayurvedic medicine for their dense vitamin and mineral content.",
    medicinalUses: ["Rich in vitamins and antioxidants", "Supports immune function", "May help regulate blood sugar"],
    activeCompounds: ["Quercetin", "Chlorogenic acid", "Isothiocyanates"],
    precautions: "Root and bark should be avoided during pregnancy; leaves are generally safe.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low",
      soil: "Sandy, well-drained",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Fast",
      harvestTime: "6-8 months",
      partUsed: "Leaf, pod",
    },
    images: [],
    studiesCited: 36,
  },
  {
    commonName: "Amla (Indian Gooseberry)",
    hindiName: "आंवला",
    botanicalName: "Phyllanthus emblica",
    sanskritName: "Amalaki",
    family: "Phyllanthaceae",
    origin: "India",
    category: "Immunity",
    tags: ["Immunity", "Skin Care", "Digestion"],
    description: "One of Ayurveda's most revered fruits, exceptionally rich in vitamin C, used for centuries to support immunity, digestion, and hair/skin health.",
    medicinalUses: ["Very high in vitamin C", "Supports immune function", "Aids digestion", "Traditionally used for hair health"],
    activeCompounds: ["Ascorbic acid", "Tannins", "Gallic acid", "Emblicanin"],
    precautions: "Generally safe; very high doses may cause mild GI upset.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low to Moderate",
      soil: "Well-drained, tolerates poor soil",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Slow",
      harvestTime: "Fruit in 3-4 years from planting",
      partUsed: "Fruit",
    },
    images: [],
    studiesCited: 39,
  },
  {
    commonName: "Giloy",
    hindiName: "गिलोय",
    botanicalName: "Tinospora cordifolia",
    sanskritName: "Guduchi",
    family: "Menispermaceae",
    origin: "India",
    category: "Immunity",
    tags: ["Immunity", "Fever", "Adaptogen"],
    description: "A climbing shrub central to Ayurvedic immune-support formulations, traditionally used during fevers and to build general resilience.",
    medicinalUses: ["Supports immune function", "Traditionally used during fevers", "Adaptogenic properties"],
    activeCompounds: ["Tinosporin", "Berberine", "Giloin"],
    precautions: "May lower blood sugar; consult a doctor if diabetic or pregnant.",
    careGuide: {
      sunlight: "Full Sun to Partial Shade",
      water: "Moderate",
      soil: "Well-drained loam",
      climate: ["Tropical", "Subtropical"],
      difficulty: "Moderate",
      growthRate: "Fast (climbing vine)",
      harvestTime: "1 year+ for mature stems",
      partUsed: "Stem",
    },
    images: [],
    studiesCited: 28,
  },
  {
    commonName: "Ajwain (Carom Seeds)",
    hindiName: "अजवायन",
    botanicalName: "Trachyspermum ammi",
    family: "Apiaceae",
    origin: "India",
    category: "Digestion",
    tags: ["Digestion", "Culinary", "Respiratory"],
    description: "A pungent, thyme-like spice seed used across Indian cooking and home remedies, especially for easing indigestion and bloating.",
    medicinalUses: ["Relieves indigestion and bloating", "Traditionally used for cough", "Antimicrobial properties"],
    activeCompounds: ["Thymol", "Carvacrol", "Cymene"],
    precautions: "Avoid excess during pregnancy; generally safe in culinary amounts.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Low to Moderate",
      soil: "Well-drained loam",
      climate: ["Subtropical", "Temperate"],
      difficulty: "Moderate",
      growthRate: "Moderate",
      harvestTime: "4-5 months (seed)",
      partUsed: "Seed",
    },
    images: [],
    studiesCited: 15,
  },
  {
    commonName: "Fennel",
    hindiName: "सौंफ",
    botanicalName: "Foeniculum vulgare",
    family: "Apiaceae",
    origin: "Mediterranean",
    category: "Digestion",
    tags: ["Digestion", "Culinary", "Respiratory"],
    description: "A sweet, anise-flavored seed widely chewed after meals in India as a digestive aid and breath freshener, also used in cooking and teas.",
    medicinalUses: ["Aids digestion", "Reduces bloating", "Freshens breath", "Traditionally used for infant colic"],
    activeCompounds: ["Anethole", "Fenchone", "Estragole"],
    precautions: "Generally safe in culinary amounts; avoid concentrated oil during pregnancy.",
    careGuide: {
      sunlight: "Full Sun",
      water: "Moderate",
      soil: "Well-drained loam",
      climate: ["Mediterranean", "Temperate", "Subtropical"],
      difficulty: "Easy",
      growthRate: "Moderate",
      harvestTime: "4-6 months (seed)",
      partUsed: "Seed, bulb, leaf",
    },
    images: [],
    studiesCited: 24,
  },
  {
    commonName: "Cardamom",
    hindiName: "इलायची",
    botanicalName: "Elettaria cardamomum",
    family: "Zingiberaceae",
    origin: "South India",
    category: "Digestion",
    tags: ["Digestion", "Culinary", "Respiratory"],
    description: "Known as the 'queen of spices,' this aromatic pod is central to Indian chai and desserts, and traditionally used to soothe digestion and breath.",
    medicinalUses: ["Aids digestion", "Freshens breath", "Traditionally used for respiratory comfort"],
    activeCompounds: ["Cineole", "Terpinyl acetate", "Limonene"],
    precautions: "Generally safe in culinary amounts.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "High",
      soil: "Rich, moist, well-drained",
      climate: ["Tropical"],
      difficulty: "Expert",
      growthRate: "Slow",
      harvestTime: "2-3 years",
      partUsed: "Seed pod",
    },
    images: [],
    studiesCited: 20,
  },
  {
    commonName: "Cinnamon",
    hindiName: "दालचीनी",
    botanicalName: "Cinnamomum verum",
    family: "Lauraceae",
    origin: "Sri Lanka, South India",
    category: "Blood Sugar",
    tags: ["Blood Sugar", "Culinary", "Anti-inflammatory"],
    description: "A warm, sweet bark spice widely used in cooking and traditional medicine, with notable research interest around blood sugar regulation.",
    medicinalUses: ["May support blood sugar regulation", "Anti-inflammatory properties", "Antioxidant-rich"],
    activeCompounds: ["Cinnamaldehyde", "Eugenol", "Coumarin"],
    precautions: "High doses (especially cassia cinnamon) may affect liver function; use in moderation.",
    careGuide: {
      sunlight: "Full Sun to Partial Shade",
      water: "Moderate to High",
      soil: "Rich, well-drained",
      climate: ["Tropical"],
      difficulty: "Expert",
      growthRate: "Slow",
      harvestTime: "2+ years (bark)",
      partUsed: "Bark",
    },
    images: [],
    studiesCited: 42,
  },
  {
    commonName: "Clove",
    hindiName: "लौंग",
    botanicalName: "Syzygium aromaticum",
    family: "Myrtaceae",
    origin: "Indonesia (Maluku Islands)",
    category: "Digestion",
    tags: ["Digestion", "Culinary", "Dental Care"],
    description: "A pungent flower bud spice widely used in Indian and global cooking, and traditionally applied for toothache relief due to its natural numbing properties.",
    medicinalUses: ["Relieves toothache", "Antimicrobial properties", "Aids digestion"],
    activeCompounds: ["Eugenol", "Acetyl eugenol"],
    precautions: "Concentrated clove oil can irritate skin/gums; use diluted or in culinary amounts.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "High",
      soil: "Rich, well-drained",
      climate: ["Tropical"],
      difficulty: "Expert",
      growthRate: "Slow",
      harvestTime: "4-6 years",
      partUsed: "Flower bud",
    },
    images: [],
    studiesCited: 26,
  },
  {
    commonName: "Black Pepper",
    hindiName: "काली मिर्च",
    botanicalName: "Piper nigrum",
    family: "Piperaceae",
    origin: "South India (Kerala)",
    category: "Digestion",
    tags: ["Digestion", "Culinary", "Respiratory"],
    description: "Known as the 'king of spices,' this pungent fruit is a cooking staple worldwide and is traditionally believed to enhance the absorption of other nutrients and compounds.",
    medicinalUses: ["Aids digestion", "May enhance nutrient absorption (e.g. with turmeric)", "Traditionally used for cough and cold"],
    activeCompounds: ["Piperine"],
    precautions: "Generally safe in culinary amounts; may interact with certain medications at high doses.",
    careGuide: {
      sunlight: "Partial Shade",
      water: "High",
      soil: "Rich, well-drained",
      climate: ["Tropical"],
      difficulty: "Expert",
      growthRate: "Slow (climbing vine)",
      harvestTime: "3-4 years",
      partUsed: "Fruit (peppercorn)",
    },
    images: [],
    studiesCited: 31,
  },
];

async function seedDB() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("✅ Connected to MongoDB");

    await Plant.deleteMany({});
    console.log("🗑️  Cleared existing plants");

    await Plant.insertMany(plants);
    console.log(`🌱 Inserted ${plants.length} plants`);

    process.exit();
  } catch (err) {
    console.error("❌ Error seeding data:", err);
    process.exit(1);
  }
}

seedDB();